import order from "stylelint-order";

export default {
  plugins: [order],
  rules: {
    "order/properties-order": [
      // 1. 位置
      "position",
      "inset",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",

      // 2. 布局
      "display",
      "flex",
      "flex-direction",
      "flex-wrap",
      "flex-shrink",
      "flex-grow",
      "flex-basis",
      "grid",
      "grid-template-columns",
      "grid-template-rows",
      "grid-auto-rows",
      "grid-column",
      "grid-row",
      "gap",
      "row-gap",
      "column-gap",
      "align-items",
      "align-self",
      "align-content",
      "justify-content",
      "justify-items",
      "justify-self",
      "place-items",
      "place-content",
      "float",
      "clear",

      // 3. 盒模型
      "box-sizing",
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-inline",
      "padding-block",
      "overflow",
      "overflow-x",
      "overflow-y",
      "scrollbar-width",
      "scrollbar-color",
      "scrollbar-gutter",
      "scroll-behavior",
      "overscroll-behavior",
      "overscroll-behavior-y",

      // 4. 排版
      "font",
      "font-family",
      "font-size",
      "font-weight",
      "font-style",
      "font-variant",
      "font-variant-numeric",
      "line-height",
      "letter-spacing",
      "color",
      "text-align",
      "text-overflow",
      "text-decoration",
      "text-decoration-line",
      "text-shadow",
      "text-transform",
      "white-space",
      "word-break",
      "word-spacing",
      "writing-mode",
      "direction",

      // 5. 背景
      "background",
      "background-image",
      "background-color",
      "background-position",
      "background-position-x",
      "background-position-y",
      "background-size",
      "background-repeat",
      "background-clip",
      "mask-image",

      // 6. 边框
      "border",
      "border-top",
      "border-right",
      "border-bottom",
      "border-left",
      "border-width",
      "border-style",
      "border-color",
      "border-radius",
      "outline",
      "outline-offset",
      "box-shadow",
      "backdrop-filter",

      // 7. 变换/过渡
      "transform",
      "transform-origin",
      "transition",
      "transition-property",
      "transition-duration",
      "transition-timing-function",
      "transition-delay",
      "animation",
      "animation-duration",
      "animation-iteration-count",
      "animation-timing-function",
      "animation-name",
      "view-transition-name",

      // 8. 交互
      "cursor",
      "pointer-events",
      "user-select",
      "-webkit-user-select",
      "-webkit-tap-highlight-color",
      "resize",
      "appearance",
      "app-region",

      // 9. 杂项
      "opacity",
      "visibility",
      "isolation",
      "filter",
      "mix-blend-mode",
      "content",
      "counter-reset",
      "counter-increment",
      "object-fit",
      "tab-size",
      "table-layout",
      "list-style",
      "will-change",
    ],
    "order/order": [
      "at-rules",
      "rules",
      "declarations",
      { type: "at-rule", name: "starting-style" },
    ],
  },
  overrides: [
    {
      files: ["**/*.vue", "**/*.html"],
      customSyntax: "postcss-html",
    },
  ],
};
